---
- name: install apt packages
  apt: pkg={{ item }}
  with_items:
    - git
    - libjpeg-dev
    - libpq-dev
    - memcached
    - nginx
    - python-dev
    - python-pip
    - python-psycopg2
    - python-setuptools
    - python-virtualenv
    - supervisor
- include: django.yml
- include: nginx.yml
