---
- name: install apt packages
  apt: pkg={{ item }}
  with_items:
    - libjpeg-dev
    - libpq-dev
    - python-dev
    - python-pip
    - python-psycopg2
    - rsync
- name: install pip packages
  pip: name={{ item }}
  with_items:
    - gunicorn
    - setproctitle
    - psycopg2
    - django-compressor
    - python-memcached
- name: copy project files
  synchronize:
    src: "{{ lookup('pipe', 'dirname `pwd`') }}/mezzanine_example/"
    dest: /srv/project
- name: copy scripts
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/srv/bin/{{ item }}"
    mode: "u=rwx,g=rx,o=rx"
  with_items:
    - entrypoint.sh
    - setsite.py
    - setadmin.py
    - wait_on_postgres.py
