version: "2"
services:
  memcached:
    image: ubuntu:xenial
    expose:
      - "11211"
  nginx:
    image: nginx:1.11
  mezzanine:
    image: ubuntu:xenial
    command: [/usr/local/bin/gunicorn, '0.0.0.0:8000', 'mezzanine_example.wsgi:application']
    entrypoint: [/srv/bin/entrypoint.sh]
    working_dir: /srv/project
    expose:
      - "8000"
