version: "2"
defaults:
  DATABASE_NAME: mezzanine
  DATABASE_USER: mezzanine
  DATABASE_PASSWORD: mezzanine
  ADMIN_PASSWORD: mezzanine

services:
  memcached:
    image: ubuntu:xenial
    expose:
      - "11211"
    entrypoint: [memcached]
    command: ["-m", "128"]
    user: daemon
  nginx:
    image: nginx:1.11
    command: ["nginx", "-g", "daemon off;"]
    expose:
      - "80"
      - "443"
    dev_overrides:
      links:
        - mezzanine
      volumes:
        - ${PWD}/certs:/certs
      volumes_from:
        - mezzanine
      ports:
        - "8080:80"
  mezzanine:
    image: ubuntu:xenial
    entrypoint: [/srv/bin/entrypoint.sh]
    command: [/usr/local/bin/gunicorn, '-b', '0.0.0.0:8000', 'mezzanine_example.wsgi:application']
    working_dir: /srv/project
    expose:
      - "8000"
    dev_overrides:
      links:
        - postgres
        - memcached
      depends_on:
        - postgres
        - memcached
      environment:
        SECRET_KEY: dummysecretkey
        PROJECT_DIR: /srv/project
        PROJECT_APP: mezzanine_example
        WEBSITE_DOMAIN: localhost
        ADMIN_PASSWORD: "{{ ADMIN_PASSWORD }}"
        DATABASE_NAME: "{{ DATABASE_NAME }}"
        DATABASE_USER: "{{ DATABASE_USER }}"
        DATABASE_PASSWORD: "{{ DATABASE_PASSWORD }}"
      volumes:
        - ${PWD}/static:/srv/project/static
  postgres:
    image: postgres:9.6
    dev_overrides:
      environment:
        POSTGRES_DB: "{{ DATABASE_NAME }}"
        POSTGRES_USER: "{{ DATABASE_USER }}"
        POSTGRES_PASSWORD: "{{ DATABASE_PASSWORD }}"
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        - ${PWD}/pgdata:/var/lib/postgresql/data/pgdata

