version: "2"
defaults:
  database_name: mezzanine
  database_user: mezzanine
  database_password: mezzanine
  secret_key: b495a05c396843b6b47ac944a72c92ed
  nevercache_key: b5d87bb4e17c483093296fa321056bdc
  twitter_access_token_key: 80b557a3a8d14cb7a2b91d60398fb8ce
  twitter_access_token_secret: 1974cf8419114bdd9d4ea3db7a210d90
  twitter_consumer_key: 1f1c627530b34bb58701ac81ac3fad51
  twitter_consumer_secret: 36515c2b60ee4ffb9d33d972a7ec350a
  mezzanine_proj_app: mezzanine_example
  mezzanine_proj_name: "{{ mezzanine_proj_app }}"
  locale: en_US.UTF-8
  database_host: postgres
  database_port: 5432
  live_hostname: localhost
  domains:
    - localhost
    - 127.0.0.1

services:
  #  nginx:
  #    image: nginx:1.11
  mezzanine:
    image: ubuntu:xenial
    expose:
      - "80"
    ports:
      - "8000:80"
    dev_overrides:
      depends_on:
        - postgres
  memcached:
    image: ubuntu:xenial
    expose:
      - "11211"
    ports:
      - "11211:11211"
    command: [-m, "128"]
    entrypoint: memcached
    user: daemon
  postgres:
    image: postgres:9.6
    expose:
      - "{{ database_port }}"
    ports:
      - "{{ database_port }}:{{ database_port }}"
    environment:
      POSTGRES_USER: "{{ database_user }}"
      POSTGRES_PASSWORD: "{{ database_password }}"

  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  # web:
  #   image: ubuntu:trusty
  #   ports:
  #     - "80:80"
  #   command: ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND']
  #   dev_overrides:
  #     environment:
  #       - "DEBUG=1"
  #
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
