version: "2"
services:
  memcached:
    image: ubuntu:xenial
    expose:
      - "11211"
    entrypoint: [memcached]
    command: ["-m", "128"]
    user: daemon
  nginx:
    image: nginx:1.11
  mezzanine:
    image: ubuntu:xenial
    entrypoint: [/srv/bin/entrypoint.sh]
    command: [/usr/local/bin/gunicorn, '0.0.0.0:8000', 'mezzanine_example.wsgi:application']
    working_dir: /srv/project
    expose:
      - "8000"
