version: "2"
defaults:
  database_name: mezzanine
  database_user: mezzanine
  database_password: mezzanine
  database_host: postgres
  database_port: 5432

services:
  #  nginx:
  #    image: nginx:1.11
  mezzanine:
    image: ubuntu:xenial
    expose:
      - "80"
    ports:
      - "8000:80"
    # dev_overrides:
    #   depends_on:
    #     - postgres
  # memcached:
  #   image: ubuntu:xenial
  #   expose:
  #     - "11211"
  #   ports:
  #     - "11211:11211"
  #   command: [-m, "128"]
  #   entrypoint: memcached
  #   user: daemon
  # postgres:
  #   image: postgres:9.6
  #   expose:
  #     - "{{ database_port }}"
  #   ports:
  #     - "{{ database_port }}:{{ database_port }}"
  #   environment:
  #     POSTGRES_USER: "{{ database_user }}"
  #     POSTGRES_PASSWORD: "{{ database_password }}"

  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  # web:
  #   image: ubuntu:trusty
  #   ports:
  #     - "80:80"
  #   command: ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND']
  #   dev_overrides:
  #     environment:
  #       - "DEBUG=1"
  #
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
