version: "2"
defaults:
  DATABASE_NAME: mezzanine
  DATABASE_USER: mezzanine
  DATABASE_PASSWORD: mezzanine

services:
  memcached:
    image: ubuntu:xenial
    expose:
      - "11211"
    entrypoint: [memcached]
    command: ["-m", "128"]
    user: daemon
  nginx:
    image: nginx:1.11
    dev_overrides:
      links:
        - mezzanine
      volumes_from:
        - mezzanine
      ports:
        - "8080:80"
  mezzanine:
    image: ubuntu:xenial
    entrypoint: [/srv/bin/entrypoint.sh]
    command: [/usr/local/bin/gunicorn, '-b', '0.0.0.0:8000', 'mezzanine_example.wsgi:application']
    working_dir: /srv/project
    expose:
      - "8000"
    dev_overrides:
      links:
        - memcached
        - postgres
      depends_on:
        - postgres
      environment:
        DATABASE_NAME: "{{ DATABASE_NAME }}"
        DATABASE_USER: "{{ DATABASE_USER }}"
        DATABASE_PASSWORD: "{{ DATABASE_PASSWORD }}"
  postgres:
    image: postgres:9.6
    dev_overrides:
      environment:
        POSTGRES_DB: "{{ DATABASE_NAME }}"
        POSTGRES_USER: "{{ DATABASE_USER }}"
        POSTGRES_PASSWORD: "{{ DATABASE_PASSWORD }}"

