version: "2"
services:
  memcached:
    image: ubuntu:xenial
    expose:
      - "11211"
  nginx:
    image: nginx:1.11
  mezzanine:
    image: ubuntu:xenial
    command: [/srv/bin/gunicorn, '0.0.0.0:8000']
    entrypoint: [/srv/bin/entrypoint.sh]
    expose:
      - "8000"
