---
- name: create vpc
  hosts: localhost
  gather_facts: False
  vars:
    region: us-west-1
  tasks:
    - name: create a vpc
      ec2_vpc_net:
        region: "{{ region }}"
        name: "Book example"
        cidr_block: 10.0.0.0/16
        tags:
          env: production
      register: vpc
    - debug: var=vpc


