- name: find xenial image
  hosts: localhost
  gather_facts: False
  tasks:
    - name: find the image
      ec2_ami_find:
        name: "ubuntu/images/ebs/ubuntu-trusty-14.04-amd64-server-*"
        sort: name
        sort_order: descending
        sort_end: 1
      register: ami
    - name: output image info
      debug: var=ami

